export interface RbacPermissionDefinition {
  code: string;
  name: string;
  group: string;
  description: string;
}

export const RBAC_PERMISSIONS: readonly RbacPermissionDefinition[] = [
  { code: "dashboard.view", name: "Xem dashboard", group: "dashboard", description: "Truy cập trang tổng quan" },
  { code: "reports.view", name: "Xem báo cáo", group: "reports", description: "Xem báo cáo doanh thu, top sản phẩm" },
  { code: "products.view", name: "Xem sản phẩm", group: "products", description: "Xem danh sách sản phẩm" },
  { code: "products.create", name: "Tạo sản phẩm", group: "products", description: "Thêm sản phẩm mới" },
  { code: "products.update", name: "Sửa sản phẩm", group: "products", description: "Cập nhật thông tin sản phẩm" },
  { code: "products.delete", name: "Xóa sản phẩm", group: "products", description: "Xóa sản phẩm" },
  { code: "categories.view", name: "Xem danh mục", group: "categories", description: "Xem danh sách danh mục" },
  { code: "categories.manage", name: "Quản lý danh mục", group: "categories", description: "Tạo, sửa và xóa danh mục" },
  { code: "inventory.view", name: "Xem tồn kho", group: "inventory", description: "Xem tồn kho sản phẩm" },
  { code: "inventory.manage", name: "Quản lý kho", group: "inventory", description: "Điều chỉnh tồn kho và tạo phiếu nhập" },
  { code: "inventory.history", name: "Xem lịch sử kho", group: "inventory", description: "Xem lịch sử nhập xuất" },
  { code: "suppliers.view", name: "Xem nhà cung cấp", group: "suppliers", description: "Xem danh sách nhà cung cấp" },
  { code: "suppliers.manage", name: "Quản lý nhà cung cấp", group: "suppliers", description: "Tạo, sửa và xóa nhà cung cấp" },
  { code: "stock_receipts.view", name: "Xem phiếu nhập", group: "stock_receipts", description: "Xem danh sách phiếu nhập" },
  { code: "stock_receipts.create", name: "Tạo phiếu nhập", group: "stock_receipts", description: "Tạo phiếu nhập mới" },
  { code: "stock_receipts.cancel", name: "Hủy phiếu nhập", group: "stock_receipts", description: "Hủy phiếu nhập và rollback tồn kho" },
  { code: "orders.view", name: "Xem đơn hàng", group: "orders", description: "Xem danh sách đơn hàng" },
  { code: "orders.update_status", name: "Cập nhật trạng thái đơn", group: "orders", description: "Đổi trạng thái đơn hàng" },
  { code: "orders.cancel", name: "Hủy đơn hàng", group: "orders", description: "Hủy đơn hàng" },
  { code: "wallet.view", name: "Xem ví và rút tiền", group: "wallet", description: "Xem số dư ví và yêu cầu rút tiền của khách" },
  { code: "wallet.manage", name: "Xử lý rút tiền", group: "wallet", description: "Duyệt, từ chối và xác nhận chuyển khoản yêu cầu rút tiền" },
  { code: "customers.view", name: "Xem khách hàng", group: "customers", description: "Xem danh sách khách hàng" },
  { code: "customers.manage", name: "Quản lý khách hàng", group: "customers", description: "Khóa và mở khách hàng" },
  { code: "banners.manage", name: "Quản lý banner", group: "marketing", description: "Quản lý banner trang chủ" },
  { code: "collections.manage", name: "Quản lý bộ sưu tập", group: "marketing", description: "Quản lý bộ sưu tập sản phẩm" },
  { code: "lookbook.manage", name: "Quản lý lookbook", group: "marketing", description: "Quản lý lookbook" },
  { code: "coupons.manage", name: "Quản lý mã giảm giá", group: "marketing", description: "Quản lý coupon" },
  { code: "promotions.manage", name: "Quản lý khuyến mãi", group: "marketing", description: "Quản lý chương trình khuyến mãi" },
  { code: "flash_sales.manage", name: "Quản lý flash sale", group: "marketing", description: "Quản lý flash sale" },
  { code: "homepage.manage", name: "Quản lý trang chủ", group: "marketing", description: "Quản lý section trang chủ" },
  { code: "pages.manage", name: "Quản lý trang tĩnh", group: "marketing", description: "Quản lý trang nội dung" },
  { code: "menus.manage", name: "Quản lý menu", group: "marketing", description: "Quản lý menu điều hướng" },
  { code: "reviews.view", name: "Xem đánh giá", group: "reviews", description: "Xem đánh giá sản phẩm" },
  { code: "reviews.moderate", name: "Duyệt đánh giá", group: "reviews", description: "Duyệt hoặc từ chối đánh giá" },
  { code: "attributes.manage", name: "Quản lý thuộc tính", group: "attributes", description: "Quản lý size, màu và chất liệu" },
  { code: "settings.view", name: "Xem cài đặt", group: "settings", description: "Xem cài đặt cửa hàng" },
  { code: "settings.manage", name: "Quản lý cài đặt", group: "settings", description: "Thay đổi cài đặt cửa hàng" },
  { code: "staff.view", name: "Xem nhân viên", group: "staff", description: "Xem danh sách nhân viên" },
  { code: "staff.manage", name: "Quản lý nhân viên", group: "staff", description: "Thêm, sửa và khóa nhân viên" },
  { code: "roles.manage", name: "Quản lý vai trò", group: "staff", description: "Cấu hình quyền cho vai trò" },
  { code: "chat.view", name: "Xem hội thoại hỗ trợ", group: "support", description: "Xem inbox và lịch sử chat" },
  { code: "chat.reply", name: "Trả lời hội thoại", group: "support", description: "Nhận phiên và trả lời khách" },
  { code: "chat.manage", name: "Quản lý hội thoại", group: "support", description: "Gán, đóng và quản lý phiên chat" },
];

export const RBAC_PERMISSION_CODES = RBAC_PERMISSIONS.map((permission) => permission.code);

export const RBAC_ROLE_PERMISSIONS: Readonly<Record<string, readonly string[]>> = {
  admin: RBAC_PERMISSION_CODES,
  warehouse_manager: [
    "dashboard.view",
    "products.view",
    "inventory.view",
    "inventory.manage",
    "inventory.history",
    "suppliers.view",
    "suppliers.manage",
    "stock_receipts.view",
    "stock_receipts.create",
    "stock_receipts.cancel",
    "reports.view",
  ],
  sales_staff: [
    "dashboard.view",
    "orders.view",
    "orders.update_status",
    "orders.cancel",
    "customers.view",
    "customers.manage",
    "products.view",
    "reviews.view",
    "reviews.moderate",
    "chat.view",
    "chat.reply",
    "reports.view",
  ],
  marketing_staff: [
    "dashboard.view",
    "banners.manage",
    "collections.manage",
    "lookbook.manage",
    "coupons.manage",
    "promotions.manage",
    "flash_sales.manage",
    "homepage.manage",
    "pages.manage",
    "menus.manage",
    "products.view",
    "reports.view",
  ],
};
